# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: iso
services:
  mariadb:
    extends:
      file: ./mariadb.yml
      service: mariadb
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
